players:
  # <id>: // A unique id (integer) for the player
  #   gamepadMapping: // The mapping of the gamepad
  #     axes: // The mapping of the axes (negative index means the axis is inverted; -0 does not work, use -0.0 instead)
  #       horizontal: <integer> // The axis index of the horizontal axis
  #       vertical: <integer> // The axis index of the vertical axis
  #       invertHorizontal: <boolean> // Whether the horizontal axis is inverted
  #       invertVertical: <boolean> // Whether the vertical axis is inverted
  #     buttons: // The mapping of the buttons
  #       up: <integer> // The id of the up button
  #       down: <integer> // The id of the down button
  #       left: <integer> // The id of the left button
  #       right: <integer> // The id of the right button
  #       action: <integer> // The id of the action button
  #       lang: <integer> // The id of the lang button
  1:
    gamepadMapping:
      axes:
        horizontal: 0
        vertical: 1
        invertHorizontal: false
        invertVertical: false

      buttons:
        action: 1
        lang: 9
