game:
  languages: ['de', 'en']
  defaultLanguage: en
  duration: 300
  introTimeout: 30
  endingTimeout: 30
  maxActiveQuests: 3
  playerAppWidth: 1024
  playerAppHeight: 768
  playerAppFontRatio: 0.0175
  devModeShortcuts: true
  userModeShortcuts: true
  canSwitchQuests: true
  cameraPresets:
    walking:
      offset:
        x: 0
        y: -1.35
      zoom: 0.70
    talking:
      offset:
        x: 0
        y: -0.8
      zoom: 1
    drone:
      offset:
        x: 0
        y: 0
      zoom: 0.5
